import turtle
import time


def triangle():
    turtle.reset()
    turtle.down()
    turtle.forward(120)
    turtle.right(120)
    turtle.forward(120)
    turtle.right(120)
    turtle.forward(120)
    turtle.up()

    turtle.color('yellow')
    turtle.down()
    turtle.forward(120)
    turtle.right(120)
    turtle.forward(120)
    turtle.right(120)
    turtle.forward(120)
    turtle.up()

    turtle.color('red')
    turtle.down()
    turtle.begin_fill()
    turtle.forward(120)
    turtle.right(120)
    turtle.forward(120)
    turtle.right(120)
    turtle.forward(120)
    turtle.end_fill()
    turtle.up()

    time.sleep(1)

    turtle.clear()


def square():
    turtle.reset()
    turtle.down()
    turtle.color('black')
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.left(135)
    turtle.forward(140)
    turtle.left(135)
    turtle.up()
    turtle.forward(100)
    turtle.down()
    turtle.left(135)
    turtle.forward(140)
    turtle.up()
    time.sleep(1)
    turtle.clear()

    turtle.down()
    turtle.left(180)
    turtle.forward(140)
    turtle.up()
    turtle.left(135)
    turtle.forward(100)
    turtle.left(135)
    turtle.down()
    turtle.forward(140)
    turtle.up()
    turtle.right(45)
    time.sleep(1)
    turtle.clear()

    turtle.left(7)
    turtle.down()
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.up()
    time.sleep(1)


def circles():
    turtle.reset()
    turtle.circle(50)
    turtle.left(180)
    turtle.circle(50)
    time.sleep(1)
    turtle.clear()

    turtle.circle(50)
    turtle.left(90)
    turtle.up()
    turtle.forward(10)
    turtle.down()
    turtle.circle(50)
    time.sleep(1)
    turtle.clear()


def pic():
    turtle.reset()

    turtle.color('green')
    turtle.down()
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.up()
    turtle.left(180)
    turtle.forward(100)
    turtle.right(30)
    turtle.color('red')
    turtle.down()
    turtle.forward(100)
    turtle.right(120)
    turtle.forward(100)
    turtle.right(30)
    turtle.up()
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(20)
    turtle.down()
    turtle.forward(60)
    turtle.left(90)
    turtle.forward(60)
    turtle.left(90)
    turtle.forward(60)
    turtle.left(90)
    turtle.forward(60)
    turtle.up()
    turtle.left(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.down()
    turtle.forward(60)
    turtle.up()
    turtle.left(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.down()
    turtle.forward(60)
    turtle.up()
    turtle.forward(1000)


triangle()
square()
circles()
pic()
